// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from group.proto

package io.protostuff.core;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.api.Input;
import io.protostuff.api.Output;
import io.protostuff.api.Schema;
import io.protostuff.api.WireFormat;

public final class Club implements Externalizable {

	public static Schema<Club> getSchema() {
		return SCHEMA;
	}

	// non-private fields
	// see http://developer.android.com/guide/practices/design/performance.html#package_inner
	String name;
	List<Student> student;
	List<Club> partnerClub;

	public Club() {

	}

	// getters and setters

	// name

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	// student

	public List<Student> getStudentList() {
		return student;
	}

	public void setStudentList(List<Student> student) {
		this.student = student;
	}

	public Student getStudent(int index) {
		return student == null ? null : student.get(index);
	}

	public int getStudentCount() {
		return student == null ? 0 : student.size();
	}

	public void addStudent(Student student) {
		if (this.student == null) {
			this.student = new ArrayList<>();
		}
		this.student.add(student);
	}

	// partnerClub

	public List<Club> getPartnerClubList() {
		return partnerClub;
	}

	public void setPartnerClubList(List<Club> partnerClub) {
		this.partnerClub = partnerClub;
	}

	public Club getPartnerClub(int index) {
		return partnerClub == null ? null : partnerClub.get(index);
	}

	public int getPartnerClubCount() {
		return partnerClub == null ? 0 : partnerClub.size();
	}

	public void addPartnerClub(Club partnerClub) {
		if (this.partnerClub == null) {
			this.partnerClub = new ArrayList<>();
		}
		this.partnerClub.add(partnerClub);
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, getSchema());
	}

	@Override
	public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
		GraphIOUtil.mergeDelimitedFrom(in, this, getSchema());
	}

	static final Schema<Club> SCHEMA = new Schema<>() {
		private static final int NAME_TAG = 1 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
		private static final int STUDENT_TAG = 2 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
		private static final int STUDENT_GROUP = 2 << 3 | WireFormat.WIRETYPE_START_GROUP;
		private static final int PARTNERCLUB_TAG = 3 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
		private static final int PARTNERCLUB_GROUP = 3 << 3 | WireFormat.WIRETYPE_START_GROUP;

		// schema methods

		@Override
		public Club newMessage() {
			return new Club();
		}

		public int tag(String name) {
			switch (name) {
				case "name":
					return NAME_TAG;
				case "student":
					return STUDENT_TAG;
				case "partenerClub":
					return PARTNERCLUB_TAG;
				default:
					return 0;
			}
		}

		@Override
		public void mergeFrom(Input input, Club message) throws IOException {
			while (true) {
				int tag = input.readTag();
				switch (tag) {
					case 0:
						return;
					case NAME_TAG:
						message.name = input.readString();
						break;
					case STUDENT_TAG:
						if (message.student == null) {
							message.student = new ArrayList<>();
						}
						message.student.add(input.mergeObject(null, Student.getSchema()));
						break;
					case STUDENT_GROUP:
						if (message.student == null) {
							message.student = new ArrayList<>();
						}
						message.student.add(input.mergeGroup(null, Student.getSchema()));
						break;
					case PARTNERCLUB_TAG:
						if (message.partnerClub == null) {
							message.partnerClub = new ArrayList<>();
						}
						message.partnerClub.add(input.mergeObject(null, Club.getSchema()));
						break;
					case PARTNERCLUB_GROUP:
						if (message.partnerClub == null) {
							message.partnerClub = new ArrayList<>();
						}
						message.partnerClub.add(input.mergeGroup(null, Club.getSchema()));
						break;
					default:
						input.skipField();
				}
			}
		}

		@Override
		public void writeTo(Output output, Club message) throws IOException {
			if (message.name != null) {
				output.writeString(NAME_TAG, "name", message.name);
			}

			if (message.student != null) {
				output.writeMessageList(STUDENT_TAG, "student", message.student, Student.getSchema());
			}

			if (message.partnerClub != null) {
				output.writeMessageList(PARTNERCLUB_TAG, "partnerClub", message.partnerClub, Club.getSchema());
			}
		}
	};

}
