// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from group.proto

package io.protostuff.core;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.api.Input;
import io.protostuff.api.Output;
import io.protostuff.api.Schema;
import io.protostuff.api.WireFormat;

public final class ClubFounder implements Externalizable {

	public static Schema<ClubFounder> getSchema() {
		return SCHEMA;
	}

	// non-private fields
	// see http://developer.android.com/guide/practices/design/performance.html#package_inner
	String name;
	Club club;

	public ClubFounder() {

	}

	// getters and setters

	// name

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	// club

	public Club getClub() {
		return club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, getSchema());
	}

	@Override
	public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
		GraphIOUtil.mergeDelimitedFrom(in, this, getSchema());
	}

	static final Schema<ClubFounder> SCHEMA = new Schema<>() {
		private static final int NAME_TAG = 1 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
		private static final int CLUB_TAG = 2 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
		private static final int CLUB_GROUP = 2 << 3 | WireFormat.WIRETYPE_START_GROUP;
		// schema methods

		@Override
		public ClubFounder newMessage() {
			return new ClubFounder();
		}

		public int tag(String name) {
			switch (name) {
				case "name":
					return NAME_TAG;
				case "club":
					return CLUB_TAG;
				default:
					return 0;
			}
		}

		@Override
		public void mergeFrom(Input input, ClubFounder message) throws IOException {
			while (true) {
				int tag = input.readTag();
				switch (tag) {
					case 0:
						return;
					case NAME_TAG:
						message.name = input.readString();
						break;
					case CLUB_TAG:
						message.club = input.mergeObject(message.club, Club.getSchema());
						break;
					case CLUB_GROUP:
						message.club = input.mergeGroup(message.club, Club.getSchema());
						break;
					default:
						input.skipField();
				}
			}
		}

		@Override
		public void writeTo(Output output, ClubFounder message) throws IOException {
			if (message.name != null) {
				output.writeString(NAME_TAG, "name", message.name);
			}

			if (message.club != null) {
				output.writeMessage(CLUB_TAG, "club", message.club, Club.getSchema());
			}

		}
	};
}
