// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from repeated.proto

package io.protostuff.core;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.api.Input;
import io.protostuff.api.Output;
import io.protostuff.api.Schema;
import io.protostuff.api.WireFormat;

public final class PojoWithRepeated implements Externalizable, Schema<PojoWithRepeated> {

	public static Schema<PojoWithRepeated> getSchema() {
		return DEFAULT_INSTANCE;
	}

	static final PojoWithRepeated DEFAULT_INSTANCE = new PojoWithRepeated();

	private List<Integer> someInt32;
	private List<Long> someFixed64;

	public PojoWithRepeated() {

	}

	@Override
	public String toString() {
		return "PojoWithRepeated{" + "someInt32=" + someInt32 + ", someFixed64=" + someFixed64 + '}';
	}

	// getters and setters

	// someInt32

	public List<Integer> getSomeInt32List() {
		return someInt32;
	}

	public PojoWithRepeated setSomeInt32List(List<Integer> someInt32) {
		this.someInt32 = someInt32;
		return this;
	}

	public Integer getSomeInt32(int index) {
		return someInt32 == null ? null : someInt32.get(index);
	}

	public int getSomeInt32Count() {
		return someInt32 == null ? 0 : someInt32.size();
	}

	public PojoWithRepeated addSomeInt32(Integer someInt32) {
		if (this.someInt32 == null) {
			this.someInt32 = new ArrayList<>();
		}
		this.someInt32.add(someInt32);
		return this;
	}

	// someFixed64

	public List<Long> getSomeFixed64List() {
		return someFixed64;
	}

	public PojoWithRepeated setSomeFixed64List(List<Long> someFixed64) {
		this.someFixed64 = someFixed64;
		return this;
	}

	public Long getSomeFixed64(int index) {
		return someFixed64 == null ? null : someFixed64.get(index);
	}

	public int getSomeFixed64Count() {
		return someFixed64 == null ? 0 : someFixed64.size();
	}

	public PojoWithRepeated addSomeFixed64(Long someFixed64) {
		if (this.someFixed64 == null) {
			this.someFixed64 = new ArrayList<>();
		}
		this.someFixed64.add(someFixed64);
		return this;
	}

	// java serialization

	@Override
	public void readExternal(ObjectInput in) throws IOException {
		GraphIOUtil.mergeDelimitedFrom(in, this, this);
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, this);
	}

	// schema methods

	@Override
	public PojoWithRepeated newMessage() {
		return new PojoWithRepeated();
	}

	public static final int SOMEINT32_TAG = 1 << 3 | WireFormat.WIRETYPE_VARINT;
	public static final int SOMEINT32_PACK = 1 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	public static final int SOMEFIXED64_TAG = 2 << 3 | WireFormat.WIRETYPE_FIXED64;
	public static final int SOMEFIXED64_PACK = 2 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;

	@Override
	public int tag(String name) {
		switch (name) {
			case "someInt32":
				return SOMEINT32_TAG;
			case "someFixed64":
				return SOMEFIXED64_TAG;
			default:
				return 0;
		}
	}

	@Override
	public void mergeFrom(Input input, PojoWithRepeated message) throws IOException {
		try {
			while (true) {
				int tag = input.readTag();
				switch (tag) {
					case 0:
						return;
					case SOMEINT32_TAG:
					case SOMEINT32_PACK:
						if (message.someInt32 == null) {
							message.someInt32 = new ArrayList<>();
						}
						message.someInt32.add(input.readUInt32());
						break;
					case SOMEFIXED64_TAG:
					case SOMEFIXED64_PACK:
						if (message.someFixed64 == null) {
							message.someFixed64 = new ArrayList<>();
						}
						message.someFixed64.add(input.readFixed64());
						break;
					default:
						input.skipField();
				}
			}
		} finally {
			if (message.someInt32 != null) {
				message.someInt32 = java.util.Collections.unmodifiableList(message.someInt32);
			} else {
				message.someInt32 = java.util.Collections.emptyList();
			}
			if (message.someFixed64 != null) {
				message.someFixed64 = java.util.Collections.unmodifiableList(message.someFixed64);
			} else {
				message.someFixed64 = java.util.Collections.emptyList();
			}
		}
	}

	@Override
	public void writeTo(Output output, PojoWithRepeated message) throws IOException {
		if (message.someInt32 != null)
			output.writeUInt32List(SOMEINT32_PACK, "someInt32", message.someInt32);
		if (message.someFixed64 != null)
			output.writeFixed64List(SOMEFIXED64_PACK, "someFixed64", message.someFixed64);
	}
}
