// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from foo.proto

package io.protostuff.core;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import io.protostuff.api.Input;
import io.protostuff.api.Output;
import io.protostuff.api.Schema;
import io.protostuff.api.WireFormat;

public final class PojoWithInts implements Externalizable, Schema<PojoWithInts> {

	public static Schema<PojoWithInts> getSchema() {
		return DEFAULT_INSTANCE;
	}

	static final PojoWithInts DEFAULT_INSTANCE = new PojoWithInts();

	private int someUint32;
	private int someSint32;
	private int someFixed32;
	private int someSfixed32;
	private long someUint64;
	private long someSint64;
	private long someFixed64;
	private long someSfixed64;

	public PojoWithInts() {

	}

	// getters and setters

	// someUint32

	public int getSomeUint32() {
		return someUint32;
	}

	public void setSomeUint32(int someUint32) {
		this.someUint32 = someUint32;
	}

	// someSint32

	public int getSomeSint32() {
		return someSint32;
	}

	public void setSomeSint32(int someSint32) {
		this.someSint32 = someSint32;
	}

	// someFixed32

	public int getSomeFixed32() {
		return someFixed32;
	}

	public void setSomeFixed32(int someFixed32) {
		this.someFixed32 = someFixed32;
	}

	// someSfixed32

	public int getSomeSfixed32() {
		return someSfixed32;
	}

	public void setSomeSfixed32(int someSfixed32) {
		this.someSfixed32 = someSfixed32;
	}

	// someUint64

	public long getSomeUint64() {
		return someUint64;
	}

	public void setSomeUint64(long someUint64) {
		this.someUint64 = someUint64;
	}

	// someSint64

	public long getSomeSint64() {
		return someSint64;
	}

	public void setSomeSint64(long someSint64) {
		this.someSint64 = someSint64;
	}

	// someFixed64

	public long getSomeFixed64() {
		return someFixed64;
	}

	public void setSomeFixed64(long someFixed64) {
		this.someFixed64 = someFixed64;
	}

	// someSfixed64

	public long getSomeSfixed64() {
		return someSfixed64;
	}

	public void setSomeSfixed64(long someSfixed64) {
		this.someSfixed64 = someSfixed64;
	}

	// java serialization

	@Override
	public void readExternal(ObjectInput in) throws IOException {
		GraphIOUtil.mergeDelimitedFrom(in, this, this);
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, this);
	}

	// schema methods

	@Override
	public PojoWithInts newMessage() {
		return new PojoWithInts();
	}

	private static final int SOMEUINT32_TAG = 1 << 3 | WireFormat.WIRETYPE_VARINT;
	private static final int SOMEUINT32_PACK = 1 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	private static final int SOMESINT32_TAG = 2 << 3 | WireFormat.WIRETYPE_VARINT;
	private static final int SOMESINT32_PACK = 2 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	private static final int SOMEFIXED32_TAG = 3 << 3 | WireFormat.WIRETYPE_FIXED32;
	private static final int SOMEFIXED32_PACK = 3 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	private static final int SOMESFIXED32_TAG = 4 << 3 | WireFormat.WIRETYPE_FIXED32;
	private static final int SOMESFIXED32_PACK = 4 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	private static final int SOMEUINT64_TAG = 5 << 3 | WireFormat.WIRETYPE_VARINT;
	private static final int SOMEUINT64_PACK = 5 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	private static final int SOMESINT64_TAG = 6 << 3 | WireFormat.WIRETYPE_VARINT;
	private static final int SOMESINT64_PACK = 6 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	private static final int SOMEFIXED64_TAG = 7 << 3 | WireFormat.WIRETYPE_FIXED64;
	private static final int SOMEFIXED64_PACK = 7 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
	private static final int SOMESFIXED64_TAG = 8 << 3 | WireFormat.WIRETYPE_FIXED64;
	private static final int SOMESFIXED64_PACK = 8 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;

	@Override
	public int tag(String name) {
		switch (name) {
			case "someUint32":
				return SOMEUINT32_TAG;
			case "someSint32":
				return SOMESINT32_TAG;
			case "someFixed32":
				return SOMEFIXED32_TAG;
			case "someSfixed32":
				return SOMESFIXED32_TAG;
			case "someUint64":
				return SOMEUINT64_TAG;
			case "someSint64":
				return SOMESINT64_TAG;
			case "someFixed64":
				return SOMEFIXED64_TAG;
			case "someSfixed64":
				return SOMESFIXED64_TAG;
			default:
				return 0;
		}
	}

	@Override
	public void mergeFrom(Input input, PojoWithInts message) throws IOException {
		while (true) {
			int tag = input.readTag();
			switch (tag) {
				case 0:
					return;
				case SOMEUINT32_TAG:
				case SOMEUINT32_PACK:
					message.someUint32 = input.readUInt32();
					break;
				case SOMESINT32_TAG:
				case SOMESINT32_PACK:
					message.someSint32 = input.readSInt32();
					break;
				case SOMEFIXED32_TAG:
				case SOMEFIXED32_PACK:
					message.someFixed32 = input.readFixed32();
					break;
				case SOMESFIXED32_TAG:
				case SOMESFIXED32_PACK:
					message.someSfixed32 = input.readFixed32();
					break;
				case SOMEUINT64_TAG:
				case SOMEUINT64_PACK:
					message.someUint64 = input.readUInt64();
					break;
				case SOMESINT64_TAG:
				case SOMESINT64_PACK:
					message.someSint64 = input.readSInt64();
					break;
				case SOMEFIXED64_TAG:
				case SOMEFIXED64_PACK:
					message.someFixed64 = input.readFixed64();
					break;
				case SOMESFIXED64_TAG:
				case SOMESFIXED64_PACK:
					message.someSfixed64 = input.readFixed64();
					break;
				default:
					input.skipField();
			}
		}
	}

	@Override
	public void writeTo(Output output, PojoWithInts message) throws IOException {
		if (message.someUint32 != 0)
			output.writeUInt32(SOMEUINT32_TAG, "someUint32", message.someUint32);
		if (message.someSint32 != 0)
			output.writeSInt32(SOMESINT32_TAG, "someSint32", message.someSint32);
		if (message.someFixed32 != 0)
			output.writeFixed32(SOMEFIXED32_TAG, "someFixed32", message.someFixed32);
		if (message.someSfixed32 != 0)
			output.writeFixed32(SOMESFIXED32_TAG, "someSfixed32", message.someSfixed32);
		if (message.someUint64 != 0)
			output.writeUInt64(SOMEUINT64_TAG, "someUint64", message.someUint64);
		if (message.someSint64 != 0)
			output.writeSInt64(SOMESINT64_TAG, "someSint64", message.someSint64);
		if (message.someFixed64 != 0)
			output.writeFixed64(SOMEFIXED64_TAG, "someFixed64", message.someFixed64);
		if (message.someSfixed64 != 0)
			output.writeFixed64(SOMESFIXED64_TAG, "someSfixed64", message.someSfixed64);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + someFixed32;
		result = prime * result + (int) (someFixed64 ^ (someFixed64 >>> 32));
		result = prime * result + someSfixed32;
		result = prime * result + (int) (someSfixed64 ^ (someSfixed64 >>> 32));
		result = prime * result + someSint32;
		result = prime * result + (int) (someSint64 ^ (someSint64 >>> 32));
		result = prime * result + someUint32;
		result = prime * result + (int) (someUint64 ^ (someUint64 >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if ((obj == null) || (getClass() != obj.getClass())) {
			return false;
		}
		PojoWithInts other = (PojoWithInts) obj;
		if (someFixed32 != other.someFixed32) {
			return false;
		}
		if (someFixed64 != other.someFixed64) {
			return false;
		}
		if (someSfixed32 != other.someSfixed32) {
			return false;
		}
		if (someSfixed64 != other.someSfixed64) {
			return false;
		}
		if (someSint32 != other.someSint32) {
			return false;
		}
		if (someSint64 != other.someSint64) {
			return false;
		}
		if (someUint32 != other.someUint32) {
			return false;
		}
		if (someUint64 != other.someUint64) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
		return "PojoWithInts [someFixed32=" + someFixed32 + ", someFixed64=" + someFixed64 + ", someSfixed32=" + someSfixed32 + ", someSfixed64=" + someSfixed64
				+ ", someSint32=" + someSint32 + ", someSint64=" + someSint64 + ", someUint32=" + someUint32 + ", someUint64=" + someUint64 + "]";
	}

}
