// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from group.proto

package io.protostuff.core;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import io.protostuff.api.Input;
import io.protostuff.api.Output;
import io.protostuff.api.Schema;
import io.protostuff.api.WireFormat;

public final class Student implements Externalizable {

	public static Schema<Student> getSchema() {
		return SCHEMA;
	}

	// non-private fields
	// see http://developer.android.com/guide/practices/design/performance.html#package_inner
	String name;
	List<Club> club;

	public Student() {

	}

	// getters and setters

	// name

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	// club

	public List<Club> getClubList() {
		return club;
	}

	public void setClubList(List<Club> club) {
		this.club = club;
	}

	public Club getClub(int index) {
		return club == null ? null : club.get(index);
	}

	public int getClubCount() {
		return club == null ? 0 : club.size();
	}

	public void addClub(Club club) {
		if (this.club == null) {
			this.club = new ArrayList<>();
		}
		this.club.add(club);
	}

	@Override
	public void writeExternal(ObjectOutput out) throws IOException {
		GraphIOUtil.writeDelimitedTo(out, this, getSchema());
	}

	@Override
	public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
		GraphIOUtil.mergeDelimitedFrom(in, this, getSchema());
	}

	// message method

	static final Schema<Student> SCHEMA = new Schema<Student>() {
		private static final int NAME_TAG = 1 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
		private static final int CLUB_TAG = 2 << 3 | WireFormat.WIRETYPE_LENGTH_DELIMITED;
		private static final int CLUB_GROUP = 2 << 3 | WireFormat.WIRETYPE_START_GROUP;
		// schema methods

		@Override
		public Student newMessage() {
			return new Student();
		}

		@Override
		public int tag(String name) {
			switch (name) {
				case "name":
					return NAME_TAG;
				case "club":
					return CLUB_TAG;
				default:
					return 0;
			}
		}

		@Override
		public void mergeFrom(Input input, Student message) throws IOException {
			while (true) {
				int tag = input.readTag();
				switch (tag) {
					case 0:
						return;
					case NAME_TAG:
						message.name = input.readString();
						break;
					case CLUB_TAG:
						if (message.club == null) {
							message.club = new ArrayList<>();
						}
						message.club.add(input.mergeObject(null, Club.getSchema()));
						break;
					case CLUB_GROUP:
						if (message.club == null) {
							message.club = new ArrayList<>();
						}
						message.club.add(input.mergeGroup(null, Club.getSchema()));
						break;
					default:
						input.skipField();
				}
			}
		}

		@Override
		public void writeTo(Output output, Student message) throws IOException {
			if (message.name != null) {
				output.writeString(NAME_TAG, "name", message.name);
			}

			if (message.club != null) {
				output.writeMessageList(CLUB_TAG, "club", message.club, Club.getSchema());
			}

		}

	};

}
